  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
       - joint_1
       - joint_2
       - joint_3
       - joint_4
       - joint_5
       - joint_6
    pid: {p: 100.0, i: 0.0, d: 5.0}
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_1: {trajectory: 0.1, goal: 0.1}
      joint_2: {trajectory: 0.1, goal: 0.1}
      joint_3: {trajectory: 0.1, goal: 0.1}
      joint_4: {trajectory: 0.1, goal: 0.1}
      joint_5: {trajectory: 0.1, goal: 0.1}
      joint_6: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
  
  joint1_controller:
    type: effort_controllers/JointEffortController
    joint: joint_1
    pid: {p: 50.0, i: 10.0, d: 5.0}
    
  joint2_controller:
    type: effort_controllers/JointEffortController
    joint: joint_2
    pid: {p: 50.0, i: 10.0, d: 5.0}
    
  joint3_controller:
    type: effort_controllers/JointEffortController
    joint: joint_3
    pid: {p: 50.0, i: 10.0, d: 5.0}
    
  joint4_controller:
    type: effort_controllers/JointEffortController
    joint: joint_4
    pid: {p: 50.0, i: 10.0, d: 5.0}
    
  joint5_controller:
    type: effort_controllers/JointEffortController
    joint: joint_5
    pid: {p: 50.0, i: 10.0, d: 5.0}
    
  joint6_controller:
    type: effort_controllers/JointEffortController
    joint: joint_6
    pid: {p: 50.0, i: 10.0, d: 5.0}
